<?php
function demopoly_geonames_init(){
  drupal_add_library('system','ui.autocomplete',TRUE);
  drupal_add_js(drupal_get_path('module', 'demopoly_geonames').'/demopoly_geonames.js');
}

function demopoly_geonames_menu(){
  
  $items['demopoly_geonames/autocomplete/%'] = array(
      'title' => 'Geonames',
      'page callback' => 'demopoly_geonames_autocomplete_callback',
      'access callback' => true,
      'page arguments' => array(2)
  );
  
  return $items;
}
function demopoly_geonames_get_data($key) {
  $cache_key = 'demopoly_geonames_get_data_'.$key;
  $cache = cache_get($cache_key);
  if ($cache->created) {
    return $cache->data;
  }else {
    $xml = file_get_contents('http://api.geonames.org/search?name_startsWith=london&maxRows=10&style=LONG&lang=es&username=demo');
   cache_set($cache_key,$xml); 
   return $xml;
  }
  
}
function demopoly_geonames_autocomplete_callback($keys){
  $xml = demopoly_geonames_get_data('london');
  $obj = new SimpleXMLElement($xml);

  
  $return = array();
  foreach($obj as $city){
    // $return[] = $city->name;
    $return[] = $city->message;
    // $return[] = $city;
  }
  
  print_r($return);
  
  
  // foreach($obj as $city){
    // echo '<pre>';
    // print_r ($city->name[0]);
    // echo '</pre>';
    // $return[] = $city->name;
  // }
  // echo '<pre>';
  // print_r($return);
  // echo '</pre>';
  echo drupal_json_output($return);
  exit();
}


?>
