<?php
/**
 * @file
 * Code for the demopoly_common feature.
 */
include_once('demopoly_registration.features.inc');
/**
 * implements hook_form_alter()
 */
function demopoly_registration_form_alter(&$form,&$form_state,$form_id) {
	global $user;
	$full_user = user_load($user->uid);
	$user_firstname = field_get_items('user', $full_user, 'field_firstname');
	drupal_set_title('Welcome '.$user_firstname[0]['value']);
	
	$form['#attributes'] = array('autocomplete' => 'off');
// 	unset($user->data['has_already_logged_in']);
	if ($form_id=='user_profile_form') {
	  
    unset($form['account']['current_pass']);
    $form['account']['current_pass_required_values']['#value'] = array();
    
		$form['account']['pass']['#weight'] = 0;
		$form['account']['pass']['#required'] = true;
		$form['actions']['submit']['#weight'] = 2;
    $form['#groups']['group_main']->format_settings['instance_settings']['classes'] = 'fullwidth';
    $form['account']['mail']['#attributes']['classes'][0] = 'fullwidth';
       
    $form['field_city'] = array(
    		'#type' => 'markup',
    		'#markup' => '
	    		<div id="edit-field-city" style="width: 49%; float: right;">
		    		<div class="form-item form-type-textfield form-item-field-firstname-und-0-value">
							<label for="edit-field-city-und-0-value">City <span class="form-required">*</span></label>
							<input class="text-full form-text" type="text" id="edit-field-city-und-0-value" name="field_city[und][0][value]" value="" size="60" maxlength="20" autocomplete="off">
						</div>
					</div>
    		'
    );
    $form['#group_children']['field_city']='group_main';
   
    
		if(isset($user->data['has_already_logged_in']) && $user->data['has_already_logged_in'] == TRUE){
			// IS SECOND VISIT
			$headline='Edit your private profile';
		} else {
			// IS FIRST VISIT
			$headline='Take Part';
			$f = &$form['#submit'];
			$f[]= "_demopoly_profile_edit_submit";
			//array_unshift($f, "_demopoly_profile_edit_submit");
			$form['actions']['save_and_go']=array(
					'#type'=>'submit',
					'#value'=>'Continue',
					'#name' => 'alternateClick',
					'#weight'=>1
			);
			return ;
		}
	}

	if ($form_id=='user_register_form') {
		$form['text']=array('#type'=>'markup','#markup'=>'<h1>Take part</h1>
				Do you want to take part? Please note that your participation requires the indication of some data. It contains the following two steps:
				<ol>
				<li>1. Email confirmation</li>
				<li>2. Participation and optional picture upload</li>
				</ol>
				<span class="lightweight">After having sent the below data, you\'ll get an Email including a link.
				Please copy/paste that link in order to come back and to proceed.
				Please note first that your participation is conditioned by age.
				For more information see the info-boxes and <a href="privacy">privacy</a>.</span>','#weight'=>-20);
		//$form['account']['mail']['#title']='HANS';
		$form['youth_protection']=array('#type'=>'fieldset','#title'=>'Youth protection','#weight'=>-10);
		$form['youth_protection']['youth_checkbox']=array('#type'=>'checkbox','#required'=>true,'#title'=>'I am 13 years old or older');
		$form['agree']=array('#type'=>'fieldset','#title'=>'Terms and conditions','#weight'=>10);
		$form['agree']['agree_checkbox']=array('#type'=>'checkbox','#required'=>true,
		'#title'=>'I agree to all terms and conditions ( <a href="/terms" class="terms-link">terms </a>/ <a href="/privacy" class="terms-link"> privacy</a> )');
		$form['#submit'][]='_demopoly_registration_submit';
	}
}
/**
 * implements hook_menu()
 */
function demopoly_registration_menu() {
	$items['user/register/thanks'] = array(
			'title' => 'Thank you for participatin',
			'description' => "",
			'page callback' => '_demopoly_profile_thanks',
			'access callback' => true,
			'type' => MENU_CALLBACK,
	);
	return $items;
}
function _demopoly_profile_thanks() {
	global $user;
	return '<h1>...Take part...</h1><h2>Hello</h2><div class="thanks-flow">thank you for taking part. You\'ve received an Email. Please click on the link in your Email in order to come back and to go on.
	';
}
function demopoly_registration_init(){
	global $user;

	if($user->uid > 1){
		if(!isset($user->data['has_already_logged_in'])
		&& arg(0) != 'file'
		&& arg(0) != 'system'
		&& arg(0) != 'profilepicture'
		&& arg(0) != 'files'
		&& (arg(0) == 'user' && arg(2) != 'edit')
		&& (arg(0) == 'user' && arg(1) != 'logout')
		&& arg(0) != 'sites') {
			drupal_goto('user/'.$user->uid.'/edit');
		}
	}
}
function _demopoly_registration_submit($form, &$form_state) {
	$form_state['redirect']='user/register/thanks';
}
function _demopoly_profile_edit_submit_forward($form, &$form_state) {
  global $user;
	$form_state['values']['signature'] = 'registration_complete';
	user_profile_form_submit($form, $form_state);
	$form_state['redirect']=array('user',array('fragment'=>'add-protest'));
}
function _demopoly_profile_edit_submit($form, &$form_state) {
	global $user;
  $edit = array(
   'data' => array(
     'has_already_logged_in' => TRUE
   )
  );
  $user = user_save($user, $edit);
  
  if($form_state['clicked_button']['#name'] == 'alternateClick'){
  	$form_state['redirect']=array('user',array('fragment'=>'add-protest'));
  }  
	$form_state['values']['signature'] = 'registration_complete';
}

function demopoly_registration_menu_alter(&$items) {
	$items['user/reset/%/%/%']['page arguments'] = array('demopoly_registration_pass_reset', 2, 3, 4);

}
function demopoly_registration_pass_reset($form, &$form_state, $uid, $timestamp, $hashed_pass, $action = NULL) {
	global $user;

	// When processing the one-time login link, we have to make sure that a user
	// isn't already logged in.
	if ($user->uid) {
		// The existing user is already logged in.
		if ($user->uid == $uid) {
			drupal_set_message(t('You are logged in as %user. <a href="!user_edit">Change your password.</a>', array('%user' => $user->name, '!user_edit' => url("user/$user->uid/edit"))));
		}
		// A different user is already logged in on the computer.
		else {
			$reset_link_account = user_load($uid);
			if (!empty($reset_link_account)) {
				drupal_set_message(t('Another user (%other_user) is already logged into the site on this computer, but you tried to use a one-time link for user %resetting_user. Please <a href="!logout">logout</a> and try using the link again.',
				array('%other_user' => $user->name, '%resetting_user' => $reset_link_account->name, '!logout' => url('user/logout'))));
			} else {
				// Invalid one-time link specifies an unknown user.
				drupal_set_message(t('The one-time login link you clicked is invalid.'));
			}
		}
		drupal_goto();
	}	else {
		// Time out, in seconds, until login URL expires. 24 hours = 86400 seconds.
		$timeout = 86400;
		$current = REQUEST_TIME;
		// Some redundant checks for extra security ?
		$users = user_load_multiple(array($uid), array('status' => '1'));
		if ($timestamp <= $current && $account = reset($users)) {
			// No time out for first time login.
			if ($account->login && $current - $timestamp > $timeout) {
				drupal_set_message(t('You have tried to use a one-time login link that has expired. Please request a new one using the form below.'));
				drupal_goto('user/password');
			}
			elseif ($account->uid && $timestamp >= $account->login && $timestamp <= $current && $hashed_pass == user_pass_rehash($account->pass, $timestamp, $account->login)) {
				// First stage is a confirmation form, then login
				if ($action == 'login') {
					watchdog('user', 'User %name used one-time login link at time %timestamp.', array('%name' => $account->name, '%timestamp' => $timestamp));
					// Set the new user.
					$user = $account;
					// user_login_finalize() also updates the login timestamp of the
					// user, which invalidates further use of the one-time login link.
					user_login_finalize();
					//drupal_set_message(t('You have just used your one-time login link. It is no longer necessary to use this link to log in. Please change your password.'));
					// Let the user's password be changed without the current password check.
					$token = drupal_hash_base64(drupal_random_bytes(55));
					$_SESSION['pass_reset_' . $user->uid] = $token;
					//drupal_goto('registration/people/first');
					drupal_goto('user/' . $user->uid . '/edit', array('query' => array('pass-reset-token' => $token)));
				}
				else {
					$form['message'] = array('#markup' => t('<p>This is a one-time login for %user_name and will expire on %expiration_date.</p><p>Click on this button to log in to the site and change your password.</p>', array('%user_name' => $account->name, '%expiration_date' => format_date($timestamp + $timeout))));
					$form['help'] = array('#markup' => '<p>' . t('This login can be used only once.') . '</p>');
					$form['actions'] = array('#type' => 'actions');
					$form['actions']['submit'] = array('#type' => 'submit', '#value' => t('Log in'));
					$form['#action'] = url("user/reset/$uid/$timestamp/$hashed_pass/login");
					drupal_goto("user/reset/$uid/$timestamp/$hashed_pass/login");
					return $form;
				}
			}
			else {
				drupal_set_message(t('You have tried to use a one-time login link that has either been used or is no longer valid. Please request a new one using the form below.'));
				drupal_goto('user/password');
			}
		}
		else {
			// Deny access, no more clues.
			// Everything will be in the watchdog's URL for the administrator to check.
			drupal_access_denied();
		}
	}
}

?>