<?php
/**
 * @file
 * Code for the demopoly_profile feature.
 */

include_once('demopoly_profile.features.inc');
/**
 * implements hook_menu()
 */
function demopoly_profile_menu() {
	$items['user/my_images/reload'] = array(
			'title' => 'Reload',
			'description' => "",
			'page callback' => '_demopoly_menu_reload',
			'access callback' => true,
			'type' => MENU_CALLBACK,
			'#ajax' => array(
					'method' => 'html',
			)
	);
  $items['user/delete'] = array(
      'title' => 'Delete Profile!',      
      'page callback' => 'drupal_get_form',
      'page arguments' => array('_demopoly_profile_delete_form'),
      'access callback' => true
  );
  $items['profile/close_callback'] = array(
      'title' => 'Demopoly',
      'page callback' => 'demopoly_profile_close_callback',
      'page arguments' => array(),
      'access callback' => true,
      'type' => MENU_CALLBACK,
  );
	return $items;
}

function _demopoly_menu_reload() {
	global $user;
	$commands = array();
	$view = views_embed_view('my_images','default',$user->uid);
	$commands[] = ajax_command_replace('.view-my-images', $view);
	$page = array('#type' => 'ajax', '#commands' => $commands);
	ajax_deliver($page);
}

function demopoly_profile_close_callback() {
  drupal_add_js('
  window.setTimeout("closeIt()", 10000);
  closeIt = function(){
    window.top.location = "/";
    top.jQuery.fn.colorbox.close();
  }', 'inline');
  return '
  <div class="markup-wrap">
    <h2 class="delete-success">Your account was successfully deleted!</h2>
    <span>This message will close in about 10 seconds and redirect you to our frontpage.</span>
  </div>';
}

function _demopoly_profile_delete_form_submit($form,&$form_state) {
  global $user;
  $uid = $user->uid;
  
  $result = db_select('demopoly_protest', 'd')
  ->condition('d.uid', $uid,'=')
  ->fields('d', array('pid'));
  foreach($result->execute() as $prot){
  	entity_delete('protest', $prot->pid);
  }
  user_delete($user->uid); // Uncomment to Delete User by ID
  $form_state['redirect']='profile/close_callback';
}

function _demopoly_profile_delete_form() {
  $form['markup-wrap-start']=array(
    '#type'=>'markup',
    '#markup'=>t('<div class="markup-wrap">')
  );
  $form['text']=array(
   '#type'=>'markup',
   '#markup'=>t('<h2>Do you really like to delete your profile?</h2>')
  );
  $form['submit']=array(
      '#type'=>'submit',
      '#value'=>t('Yes')
  );
  $form['button-wrap-start']=array(
    '#type'=>'markup',
    '#markup'=>t('<div class="button-wrap">')
  );
  $form['yes']=array(
      '#type'=>'markup',
      '#markup'=>t('<a href="#Yes" class="button medium delete-yes">Yes</a>')
  );
  $form['no']=array(
      '#type'=>'markup',
      '#markup'=>t('<a href="#No" class="button medium delete-no">No</a>')
  );
  $form['markup-wrap-end']=array(
    '#type'=>'markup',
    '#markup'=>t('</div><span class="footnote delete-warn">WARNING: This action can not be reverted!</span></div>')
  );
  $form['script']=array(
      '#type'=>'markup',
      '#markup'=>t('
        <script type="text/javascript">
          (function($){
            Drupal.behaviors.demopoly_protest = {
              attach:function(context){
                $(".button.delete-yes").click(function() {
                  $("form").submit();
                });
                $(".button.delete-no").click(function() {
                  top.jQuery.colorbox.close();
                });
              }}
          })(jQuery);
        </script>
      ')
  );
  return $form;
}
