<?php

/**
 * @file
 * Geoname example form element
 */

/**
 *
 */
function geonames_tools_menu() {
  $items['geonames/autocomplete'] = array(
    'title'   => 'Autocomplete Geonames Search',
    'page callback' => 'geonames_tools_search_autocomplete',
    'access arguments' => array('access content'),
    'type'    => MENU_CALLBACK,
  );

  return $items;
}

/**
 *
 */
function geonames_tools_search_form() {
  $form['search'] = array(
    '#type'              => 'textfield',
    '#title'             => t('Location Search'),
    '#description'       => t('Search for location'),
    '#autocomplete_path' => 'geonames/autocomplete',
  );
  $form['submit'] = array(
    '#type' => 'value',
    '#value' => TRUE,
  );

  return $form;
}

/**
 *
 */
function geonames_tools_search_autocomplete($search) {
  $matches = array();
  $query = array(
    'query' => $search,
    'maxrows' => 15,
    'featureclass' => array('P'),
    'featurecode' => array('PPL', 'PPLA', 'PPLG', 'PPLR', 'PPLC', 'PPLS', 'STLM'),
    'style' => 'full',
  );
  $result = geonames_query('search', $query);
  if ($result->total_results_count) {
    foreach ($result->results as $m) {
      $r  = $m['name'];
      $r .= ($m['adminname1']) ? ', ' . $m['adminname1'] : '';
      $r .= ($m['countryname']) ? ', ' . $m['countryname'] : '';
      $r .= " >> " . $m['lat'] . "," . $m['lng'];
      $matches[$r] = $r;
    }
  }
  print drupal_json_encode($matches);
  exit();
}
